@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class APOLICES {
   VALOR_PREMIO: number(15,3)
   VALOR_FRANQUIA: number(15,3)
   ID_APOLICE: number(10)
   NUMERO_SEGURADORA: number(10)
   ID_CLIENTE: number(10)
}
class CAMINHOES {
   MARCA: varchar2(64)
   MODELO: varchar2(64)
   ANO_FABRICACAO: number(4)
   PLACA: nchar(7)
}
class CATEGORIAS_ITEM {
   DESCRICAO: varchar2(256)
   ID_CATEGORIA: number(10)
}
class CATEGORIZACOES {
   ID_ITEM: number(10)
   ID_CATEGORIA: number(10)
}
class CIDADES {
   NOME: varchar2(64)
   UNIDADE_FEDERATIVA: nchar(2)
   ID_CIDADE: number(10)
}
class CLIENTES {
   NOME: varchar2(64)
   ID_CLIENTE: number(10)
}
class CONDUCOES {
   ID_ENTREGA: number(10)
   CNH: number(11)
}
class DISTANCIAS {
   DISTANCIA: number(10)
   ID_CIDADE_PARTIDA: number(10)
   ID_CIDADE_CHEGADA: number(10)
}
class ENDERECOS {
   CEP: number(8)
   RUA: varchar2(64)
   NUMERO: number(5)
   COMPLEMENTO: number(3)
   BAIRRO: varchar2(64)
   CIDADE: varchar2(64)
   UNIDADE_FEDERATIVA: nchar(2)
   ID_CLIENTE: number(10)
   ID_ENDERECO: number(10)
}
class ENTREGAS {
   VALOR: float(3)
   DATA_CHEGADA: date
   DATA_SAIDA: date
   ID_CIDADE_PARTIDA: number(10)
   PLACA: nchar(7)
   ID_CIDADE_CHEGADA: number(10)
   ID_CLIENTE: number(10)
   ID_ENTREGA: number(10)
}
class INSPECOES {
   DATA: date
   ID_PROTOCOLO_SEGURANCA: number(10)
   ID_ITEM: number(10)
}
class ITENS {
   DESCRICAO: varchar2(64)
   PESO: number(3)
   LARGURA: number(3)
   COMPRIMENTO: number(3)
   ALTURA: number(3)
   ID_ITEM: number(10)
}
class LICITACOES {
   ORGAO_FISCALIZADOR: varchar2(64)
   DATA_LICITACAO: date
   INDICE_LICITACAO: number(10)
   ID_ITEM: number(10)
}
class MOTORISTAS {
   DATA_CONTRATACAO: date
   NOME: varchar2(64)
   SALARIO: number(6)
   CNH: number(11)
}
class PESSOAS_FISICAS {
   CPF: number(11)
   RG: number(10)
   ID_CLIENTE: number(10)
}
class PESSOAS_JURIDICAS {
   CNPJ: number(11)
   INSCRICAO_ESTADUAL: number(10)
   ID_CLIENTE: number(10)
}
class PROTOCOLOS_SEGURANCA {
   DESCRICAO: varchar2(256)
   ID_PROTOCOLO_SEGURANCA: number(10)
}
class REMESSAS {
   VALOR_DECLARADO: number(10)
   ID_ITEM: number(10)
   ID_ENTREGA: number(10)
}
class SEGURADORAS {
   NOME: varchar2(64)
   NUMERO_SEGURADORA: number(10)
}
class TELEFONES {
   DDD: nchar(2)
   NUMERO: number(9)
   ID_CLIENTE: number(10)
   ID_TELEFONE: number(10)
}

APOLICES              -[#595959,plain]-^  PESSOAS_JURIDICAS    : ":ID_CLIENTE"
APOLICES              -[#595959,plain]-^  SEGURADORAS          : ":NUMERO_SEGURADORA"
CATEGORIZACOES        -[#595959,plain]-^  CATEGORIAS_ITEM      : ":ID_CATEGORIA"
CATEGORIZACOES        -[#595959,plain]-^  ITENS                : ":ID_ITEM"
CONDUCOES             -[#595959,plain]-^  ENTREGAS             : ":ID_ENTREGA"
CONDUCOES             -[#595959,plain]-^  MOTORISTAS           : ":CNH"
DISTANCIAS            -[#595959,plain]-^  CIDADES              : ":ID_CIDADE"
ENDERECOS             -[#595959,plain]-^  CLIENTES             : ":ID_CLIENTE"
ENTREGAS              -[#595959,plain]-^  CAMINHOES            : ":PLACA"
ENTREGAS              -[#595959,plain]-^  CIDADES              : ":ID_CIDADE"
ENTREGAS              -[#595959,plain]-^  CLIENTES             : ":ID_CLIENTE"
INSPECOES             -[#595959,plain]-^  ITENS                : ":ID_ITEM"
INSPECOES             -[#595959,plain]-^  PROTOCOLOS_SEGURANCA : ":ID_PROTOCOLO_SEGURANCA"
LICITACOES            -[#595959,plain]-^  ITENS                : ":ID_ITEM"
PESSOAS_FISICAS       -[#595959,plain]-^  CLIENTES             : ":ID_CLIENTE"
PESSOAS_JURIDICAS     -[#595959,plain]-^  CLIENTES             : ":ID_CLIENTE"
REMESSAS              -[#595959,plain]-^  ENTREGAS             : ":ID_ENTREGA"
REMESSAS              -[#595959,plain]-^  ITENS                : ":ID_ITEM"
TELEFONES             -[#595959,plain]-^  CLIENTES             : ":ID_CLIENTE"
@enduml
