SELECT
    ENTREGA.ID_ENTREGA,
    CLIENTE.NOME,
    INSPECAO.DATA AS DATA_INSPECAO,
    ITEM.DESCRICAO AS DESCRICAO_ITEM,
    PROTOCOLO_SEGURANCA.DESCRICAO AS DESCRICAO_PROTOCOLO_SEGURANCA,
    LICITACAO.INDICE_LICITACAO,
    LICITACAO.ORGAO_FISCALIZADOR,
    LICITACAO.DATA_LICITACAO AS DATA_LICITACAO
FROM CC105613.CLIENTES CLIENTE
         INNER JOIN CC105613.ENTREGAS ENTREGA ON CLIENTE.ID_CLIENTE = ENTREGA.ID_CLIENTE
                  INNER JOIN CC105613.REMESSAS REMESSA ON ENTREGA.ID_ENTREGA = REMESSA.ID_ENTREGA
                  INNER JOIN CC105613.ITENS ITEM ON REMESSA.ID_ITEM = ITEM.ID_ITEM
                  INNER JOIN CC105613.INSPECOES INSPECAO ON ITEM.ID_ITEM = INSPECAO.ID_ITEM
                  INNER JOIN CC105613.PROTOCOLOS_SEGURANCA PROTOCOLO_SEGURANCA ON INSPECAO.ID_PROTOCOLO_SEGURANCA = PROTOCOLO_SEGURANCA.ID_PROTOCOLO_SEGURANCA
                  INNER JOIN CC105613.ENDERECOS ENDERECO ON CLIENTE.ID_CLIENTE = ENDERECO.ID_CLIENTE
                  INNER JOIN CC105613.LICITACOES LICITACAO ON ITEM.ID_ITEM = LICITACAO.ID_ITEM
                  INNER JOIN CIDADES CIDADE ON CIDADE.ID_CIDADE = ENDERECO.ID_CIDADE
WHERE CIDADE.NOME = 'Porto Alegre';