SELECT
    CC105613.ENTREGAS.ID_ENTREGA,
    CLIENTE.NOME,
    INSPECAO.DATA,
    PROTOCOLO_SEGURANCA.DESCRICAO,
    LICITACAO.INDICE_LICITACAO,
    LICITACAO.ORGAO_FISCALIZADOR,
    LICITACAO.DATA_LICITACAO
FROM CC105613.ENTREGAS
         INNER JOIN CC105613.REMESSAS REMESSA ON CC105613.ENTREGAS.ID_ENTREGA = REMESSA.ID_ENTREGA
         INNER JOIN CC105613.ITENS ITEM ON REMESSA.ID_ITEM = ITEM.ID_ITEM
         INNER JOIN CC105613.PROTOCOLOS_SEGURANCA PROTOCOLO_SEGURANCA ON ITEM.DESCRICAO = PROTOCOLO_SEGURANCA.DESCRICAO
         INNER JOIN CC105613.INSPECOES INSPECAO ON ITEM.ID_ITEM = INSPECAO.ID_ITEM
         INNER JOIN CC105613.CLIENTES CLIENTE ON CC105613.ENTREGAS.ID_CLIENTE = CLIENTE.ID_CLIENTE
         INNER JOIN CC105613.ENDERECOS ENDERECO ON CLIENTE.ID_CLIENTE = ENDERECO.ID_CLIENTE
         INNER JOIN CC105613.LICITACOES LICITACAO ON ITEM.ID_ITEM = LICITACAO.ID_ITEM
WHERE ENDERECO.CIDADE = 'Porto Alegre';