--Listar o nome dos clientes, o número, a data de saída, a placa do caminhão
-- e o nome do motorista de suas entregas, bem como a descrição e o nome das
-- categorias dos itens entregues, apenas para as entregas efetuadas no corrente ano,
-- para clientes do Rio Grande do Sul e que tenham valor do prêmio de apólice de seguro
-- pelo menos R$ 100.000,00.
SELECT CLIENTE.NOME AS NOME_DO_CLIENTE,
       ENTREGA.ID_ENTREGA,
       ENTREGA.DATA_PARTIDA,
       ENTREGA.PLACA,
       MOTORISTA.NOME AS NOME_DO_MOTORISTA,
       CATEGORIA_ITEM.DESCRICAO

FROM CC105613.CLIENTES CLIENTE
         INNER JOIN CC105613.ENTREGAS ENTREGA ON CLIENTE.ID_CLIENTE = ENTREGA.ID_CLIENTE
         INNER JOIN CC105613.APOLICES APOLICE ON APOLICE.ID_ENTREGA = ENTREGA.ID_ENTREGA
         INNER JOIN CC105613.ENDERECOS ENDERECO ON CLIENTE.ID_CLIENTE = ENDERECO.ID_CLIENTE
         INNER JOIN CC105613.CAMINHOES CAMINHAO ON ENTREGA.PLACA = CAMINHAO.PLACA
         INNER JOIN CC105613.CONDUCOES CONDUCAO ON ENTREGA.ID_ENTREGA = CONDUCAO.ID_ENTREGA
         INNER JOIN CC105613.MOTORISTAS MOTORISTA ON CONDUCAO.CNH = MOTORISTA.CNH
         INNER JOIN CC105613.REMESSAS REMESSA ON ENTREGA.ID_ENTREGA = REMESSA.ID_ENTREGA
         INNER JOIN CC105613.ITENS ITEM ON ITEM.ID_ITEM = REMESSA.ID_ITEM
         INNER JOIN CC105613.CATEGORIZACOES CATEGORIZACAO ON CATEGORIZACAO.ID_ITEM = ITEM.ID_ITEM
         INNER JOIN CC105613.CATEGORIAS_ITENS CATEGORIA_ITEM ON CATEGORIZACAO.ID_CATEGORIA = CATEGORIA_ITEM.ID_CATEGORIA

WHERE EXTRACT(YEAR FROM ENTREGA.DATA_CHEGADA_PREVISTA) = EXTRACT(YEAR FROM SYSDATE)
  AND ENDERECO.UNIDADE_FEDERATIVA = 'RS'
  AND APOLICE.VALOR_PREMIO >= 100000;
