--Listar o nome de todos os clientes pessoa jurídica, acompanhados da
-- quantidade de entregas solicitadas e do valor total de suas apólices de seguro, apenas para
-- clientes do Rio Grande do Sul que tenham solicitado pelo menos 5 entregas.
SELECT CLIENTE.NOME,
       COUNT(DISTINCT ENTREGA.ID_ENTREGA) AS QUANTIDADE_ENTREGAS,
       COALESCE(SUM(DISTINCT APOLICE.VALOR_PREMIO), 0) + COALESCE(SUM(DISTINCT APOLICE.VALOR_FRANQUIA), 0) AS VALOR_TOTAL_APOLICES

FROM CC105613.PESSOAS_JURIDICAS PESSOA_JURIDICA
         INNER JOIN CC105613.CLIENTES CLIENTE ON CLIENTE.ID_CLIENTE = PESSOA_JURIDICA.ID_CLIENTE
         INNER JOIN CC105613.APOLICES APOLICE ON APOLICE.ID_CLIENTE = PESSOA_JURIDICA.ID_CLIENTE
         INNER JOIN CC105613.ENDERECOS ENDERECO ON PESSOA_JURIDICA.ID_CLIENTE = ENDERECO.ID_CLIENTE
         INNER JOIN CC105613.ENTREGAS ENTREGA ON ENTREGA.ID_CLIENTE = PESSOA_JURIDICA.ID_CLIENTE

WHERE ENDERECO.UNIDADE_FEDERATIVA = 'RS'
GROUP BY CLIENTE.NOME
HAVING COUNT(DISTINCT ENTREGA.ID_ENTREGA) >= 5
ORDER BY CLIENTE.NOME;