--Listar o nome de todos os clientes pessoa jurídica, acompanhados da
-- quantidade de entregas solicitadas e do valor total de suas apólices de seguro, apenas para
-- clientes do Rio Grande do Sul que tenham solicitado pelo menos 5 entregas.
SELECT DISTINCT
    CLIENTE.NOME,
    COUNT(ENTREGA.ID_ENTREGA) AS QTD_ENTREGAS,
    CLIENTES_APOLICES_VALOR_TOTAL.VALOR_TOTAL_APOLICES


FROM CC105613.PESSOAS_JURIDICAS PESSOA_JURIDICA
    INNER JOIN CC105613.CLIENTES CLIENTE ON CLIENTE.ID_CLIENTE = PESSOA_JURIDICA.ID_CLIENTE
    INNER JOIN CC105613.ENTREGAS ENTREGA ON ENTREGA.ID_CLIENTE = PESSOA_JURIDICA.ID_CLIENTE
    INNER JOIN CC105613.ENDERECOS ENDERECO ON ENDERECO.ID_CLIENTE = PESSOA_JURIDICA.ID_CLIENTE
    INNER JOIN
        (
            SELECT
                PESSOA_JURIDICA.ID_CLIENTE,
                CLIENTE.NOME,
                SUM(APOLICE.VALOR_PREMIO + APOLICE.VALOR_FRANQUIA) AS VALOR_TOTAL_APOLICES
            FROM
                PESSOAS_JURIDICAS PESSOA_JURIDICA
                INNER JOIN CLIENTES CLIENTE ON CLIENTE.ID_CLIENTE = PESSOA_JURIDICA.ID_CLIENTE
                LEFT JOIN APOLICES APOLICE ON PESSOA_JURIDICA.ID_CLIENTE = APOLICE.ID_CLIENTE
                GROUP BY PESSOA_JURIDICA.ID_CLIENTE, CLIENTE.NOME
        ) CLIENTES_APOLICES_VALOR_TOTAL ON CLIENTES_APOLICES_VALOR_TOTAL.ID_CLIENTE = PESSOA_JURIDICA.ID_CLIENTE

WHERE ENDERECO.UNIDADE_FEDERATIVA = 'RS'
GROUP BY CLIENTE.ID_CLIENTE, CLIENTE.NOME, CLIENTES_APOLICES_VALOR_TOTAL.VALOR_TOTAL_APOLICES
HAVING COUNT(DISTINCT ENTREGA.ID_ENTREGA) >= 5;

