CREATE TABLE CC105613.CAMINHOES
(
    PLACA          NCHAR(7)    NOT NULL,
    MARCA          VARCHAR(64) NOT NULL,
    MODELO         VARCHAR(64) NOT NULL,
    ANO_FABRICACAO NUMERIC(4)  NOT NULL
);

ALTER TABLE CC105613.CAMINHOES
    ADD CONSTRAINT PK_CAMINHOES PRIMARY KEY (PLACA);


CREATE TABLE CC105613.CATEGORIAS_ITEM
(
    ID_CATEGORIA NUMERIC(10) NOT NULL,
    DESCRICAO    VARCHAR(256)
);

ALTER TABLE CC105613.CATEGORIAS_ITEM
    ADD CONSTRAINT PK_CATEGORIAS_ITEM PRIMARY KEY (ID_CATEGORIA);


CREATE TABLE CC105613.CIDADES
(
    ID_CIDADE          NUMERIC(10) NOT NULL,
    NOME               VARCHAR(64) NOT NULL,
    UNIDADE_FEDERATIVA NCHAR(2)    NOT NULL
);

ALTER TABLE CC105613.CIDADES
    ADD CONSTRAINT PK_CIDADES PRIMARY KEY (ID_CIDADE);


CREATE TABLE CC105613.CLIENTES
(
    ID_CLIENTE NUMERIC(10) NOT NULL,
    NOME       VARCHAR(64) NOT NULL
);

ALTER TABLE CC105613.CLIENTES
    ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE);


CREATE TABLE CC105613.DISTANCIAS
(
    ID_CIDADE_PARTIDA NUMERIC(10) NOT NULL,
    ID_CIDADE_CHEGADA NUMERIC(10) NOT NULL,
    DISTANCIA         DECIMAL(10) NOT NULL
);

ALTER TABLE CC105613.DISTANCIAS
    ADD CONSTRAINT PK_DISTANCIAS PRIMARY KEY (ID_CIDADE_PARTIDA, ID_CIDADE_CHEGADA);


CREATE TABLE CC105613.ENDERECOS
(
    ID_ENDERECO        NUMERIC(10) NOT NULL,
    CEP                NUMERIC(8)  NOT NULL,
    RUA                VARCHAR(64) NOT NULL,
    NUMERO             NUMERIC(5)  NOT NULL,
    COMPLEMENTO        NUMERIC(3),
    BAIRRO             VARCHAR(64),
    CIDADE             VARCHAR(64) NOT NULL,
    UNIDADE_FEDERATIVA NCHAR(2)    NOT NULL,
    ID_CLIENTE         NUMERIC(10) NOT NULL
);

ALTER TABLE CC105613.ENDERECOS
    ADD CONSTRAINT PK_ENDERECOS PRIMARY KEY (ID_ENDERECO);


CREATE TABLE CC105613.ENTREGAS
(
    ID_ENTREGA        NUMERIC(10) NOT NULL,
    VALOR             FLOAT(3)    NOT NULL,
    DATA_CHEGADA      DATE,
    DATA_SAIDA        DATE,
    ID_CIDADE_PARTIDA NUMERIC(10),
    PLACA             NCHAR(7),
    ID_CIDADE_CHEGADA NUMERIC(10),
    ID_CLIENTE        NUMERIC(10) NOT NULL
);

ALTER TABLE CC105613.ENTREGAS
    ADD CONSTRAINT PK_ENTREGAS PRIMARY KEY (ID_ENTREGA);


CREATE TABLE CC105613.ITENS
(
    ID_ITEM     NUMERIC(10) NOT NULL,
    DESCRICAO   VARCHAR(64) NOT NULL,
    PESO        DECIMAL(3)  NOT NULL,
    LARGURA     DECIMAL(3)  NOT NULL,
    COMPRIMENTO DECIMAL(3)  NOT NULL,
    ALTURA      DECIMAL(3)  NOT NULL
);

ALTER TABLE CC105613.ITENS
    ADD CONSTRAINT PK_ITENS PRIMARY KEY (ID_ITEM);


CREATE TABLE CC105613.LICITACOES
(
    INDICE_LICITACAO   NUMERIC(10) NOT NULL,
    ID_ITEM            NUMERIC(10) NOT NULL,
    ORGAO_FISCALIZADOR VARCHAR(64),
    DATA_LICITACAO     DATE        NOT NULL
);

ALTER TABLE CC105613.LICITACOES
    ADD CONSTRAINT PK_LICITACOES PRIMARY KEY (INDICE_LICITACAO, ID_ITEM);


CREATE TABLE CC105613.MOTORISTAS
(
    CNH              NUMERIC(11) NOT NULL,
    DATA_CONTRATACAO DATE        NOT NULL,
    NOME             VARCHAR(64) NOT NULL,
    SALARIO          DECIMAL(6)  NOT NULL
);

ALTER TABLE CC105613.MOTORISTAS
    ADD CONSTRAINT PK_MOTORISTAS PRIMARY KEY (CNH);


CREATE TABLE CC105613.PESSOAS_FISICAS
(
    ID_CLIENTE NUMERIC(10) NOT NULL,
    CPF        NUMERIC(11),
    RG         NUMERIC(10)
);

ALTER TABLE CC105613.PESSOAS_FISICAS
    ADD CONSTRAINT PK_PESSOAS_FISICAS PRIMARY KEY (ID_CLIENTE);


CREATE TABLE CC105613.PESSOAS_JURIDICAS
(
    ID_CLIENTE         NUMERIC(10) NOT NULL,
    CNPJ               NUMERIC(11) NOT NULL,
    INSCRICAO_ESTADUAL NUMERIC(10) NOT NULL
);

ALTER TABLE CC105613.PESSOAS_JURIDICAS
    ADD CONSTRAINT PK_PESSOAS_JURIDICAS PRIMARY KEY (ID_CLIENTE);


CREATE TABLE CC105613.PROTOCOLOS_SEGURANCA
(
    ID_PROTOCOLO_SEGURANCA NUMERIC(10)  NOT NULL,
    DESCRICAO              VARCHAR(256) NOT NULL
);

ALTER TABLE CC105613.PROTOCOLOS_SEGURANCA
    ADD CONSTRAINT PK_PROTOCOLOS_SEGURANCA PRIMARY KEY (ID_PROTOCOLO_SEGURANCA);


CREATE TABLE CC105613.REMESSAS
(
    ID_ITEM         NUMERIC(10) NOT NULL,
    ID_ENTREGA      NUMERIC(10) NOT NULL,
    VALOR_DECLARADO DECIMAL(10)
);

ALTER TABLE CC105613.REMESSAS
    ADD CONSTRAINT PK_REMESSAS PRIMARY KEY (ID_ITEM, ID_ENTREGA);


CREATE TABLE CC105613.SEGURADORAS
(
    NUMERO_SEGURADORA NUMERIC(10) NOT NULL,
    NOME              VARCHAR(64) NOT NULL
);

ALTER TABLE CC105613.SEGURADORAS
    ADD CONSTRAINT PK_SEGURADORAS PRIMARY KEY (NUMERO_SEGURADORA);


CREATE TABLE CC105613.TELEFONES
(
    ID_TELEFONE NUMERIC(10) NOT NULL,
    DDD         NCHAR(2)    NOT NULL,
    NUMERO      NUMERIC(9)  NOT NULL,
    ID_CLIENTE  NUMERIC(10) NOT NULL
);

ALTER TABLE CC105613.TELEFONES
    ADD CONSTRAINT PK_TELEFONES PRIMARY KEY (ID_TELEFONE);


CREATE TABLE CC105613.APOLICES
(
    ID_APOLICE        NUMERIC(10)    NOT NULL,
    NUMERO_SEGURADORA NUMERIC(10)    NOT NULL,
    ID_CLIENTE        NUMERIC(10)    NOT NULL,
    ID_ENTREGA        NUMERIC(10)    NOT NULL,
    VALOR_PREMIO      DECIMAL(15, 3) NOT NULL,
    VALOR_FRANQUIA    DECIMAL(15, 3) NOT NULL
);

ALTER TABLE CC105613.APOLICES
    ADD CONSTRAINT PK_APOLICES PRIMARY KEY (ID_APOLICE, NUMERO_SEGURADORA, ID_CLIENTE);


CREATE TABLE CC105613.CATEGORIZACOES
(
    ID_ITEM      NUMERIC(10) NOT NULL,
    ID_CATEGORIA NUMERIC(10) NOT NULL
);

ALTER TABLE CC105613.CATEGORIZACOES
    ADD CONSTRAINT PK_CATEGORIZACAO PRIMARY KEY (ID_ITEM, ID_CATEGORIA);


CREATE TABLE CC105613.CONDUCOES
(
    ID_ENTREGA NUMERIC(10) NOT NULL,
    CNH        NUMERIC(11) NOT NULL
);

ALTER TABLE CC105613.CONDUCOES
    ADD CONSTRAINT PK_CONDUCAO PRIMARY KEY (ID_ENTREGA, CNH);


CREATE TABLE CC105613.INSPECOES
(
    ID_PROTOCOLO_SEGURANCA NUMERIC(10) NOT NULL,
    ID_ITEM                NUMERIC(10) NOT NULL,
    DATA                   DATE        NOT NULL
);

ALTER TABLE CC105613.INSPECOES
    ADD CONSTRAINT PK_INSPECOES PRIMARY KEY (ID_PROTOCOLO_SEGURANCA, ID_ITEM);


ALTER TABLE CC105613.DISTANCIAS
    ADD CONSTRAINT FK_CIDADE_INICIAL FOREIGN KEY (ID_CIDADE_PARTIDA) REFERENCES CIDADES (ID_CIDADE);
ALTER TABLE CC105613.DISTANCIAS
    ADD CONSTRAINT FK_CIDADE_FINAL FOREIGN KEY (ID_CIDADE_CHEGADA) REFERENCES CIDADES (ID_CIDADE);


ALTER TABLE CC105613.ENDERECOS
    ADD CONSTRAINT FK_ENDERECOES_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);


ALTER TABLE CC105613.ENTREGAS
    ADD CONSTRAINT FK_ENTREGAS_CIDADE_PARTIDA FOREIGN KEY (ID_CIDADE_PARTIDA) REFERENCES CIDADES (ID_CIDADE);
ALTER TABLE CC105613.ENTREGAS
    ADD CONSTRAINT FK_ENTREGAS_CAMINHAO FOREIGN KEY (PLACA) REFERENCES CAMINHOES (PLACA);
ALTER TABLE CC105613.ENTREGAS
    ADD CONSTRAINT FK_ENTREGAS_CIDADE FOREIGN KEY (ID_CIDADE_CHEGADA) REFERENCES CIDADES (ID_CIDADE);
ALTER TABLE CC105613.ENTREGAS
    ADD CONSTRAINT FK_ENTREGAS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);


ALTER TABLE CC105613.LICITACOES
    ADD CONSTRAINT FK_LICITACOES_ITEM FOREIGN KEY (ID_ITEM) REFERENCES ITENS (ID_ITEM);


ALTER TABLE CC105613.PESSOAS_FISICAS
    ADD CONSTRAINT FK_PESSOAS_FISICAS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);


ALTER TABLE CC105613.PESSOAS_JURIDICAS
    ADD CONSTRAINT FK_PESSOAS_JURIDICAS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);


ALTER TABLE CC105613.REMESSAS
    ADD CONSTRAINT FK_REMESSAS_ITEM FOREIGN KEY (ID_ITEM) REFERENCES ITENS (ID_ITEM);
ALTER TABLE CC105613.REMESSAS
    ADD CONSTRAINT FK_REMESSAS_ENTREGA FOREIGN KEY (ID_ENTREGA) REFERENCES ENTREGAS (ID_ENTREGA);


ALTER TABLE CC105613.TELEFONES
    ADD CONSTRAINT FK_TELEFONES_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);


ALTER TABLE CC105613.APOLICES
    ADD CONSTRAINT FK_APOLICES_SEGURADORA FOREIGN KEY (NUMERO_SEGURADORA) REFERENCES SEGURADORAS (NUMERO_SEGURADORA)
    ADD CONSTRAINT FK_APOLICES_PESSOA_JURIDICA FOREIGN KEY (ID_CLIENTE) REFERENCES PESSOAS_JURIDICAS (ID_CLIENTE)
    ADD CONSTRAINT FK_APOLICES_ENTREGA FOREIGN KEY (ID_ENTREGA) REFERENCES ENTREGAS (ID_ENTREGA);


ALTER TABLE CC105613.CATEGORIZACOES
    ADD CONSTRAINT FK_CATEGORIZACAO_ITEM FOREIGN KEY (ID_ITEM) REFERENCES ITENS (ID_ITEM);
ALTER TABLE CC105613.CATEGORIZACOES
    ADD CONSTRAINT FK_CATEGORIZACAO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS_ITEM (ID_CATEGORIA);


ALTER TABLE CC105613.CONDUCOES
    ADD CONSTRAINT FK_CONDUCAO_ENTREGA FOREIGN KEY (ID_ENTREGA) REFERENCES ENTREGAS (ID_ENTREGA);
ALTER TABLE CC105613.CONDUCOES
    ADD CONSTRAINT FK_CONDUCAO_MOTORISTA FOREIGN KEY (CNH) REFERENCES MOTORISTAS (CNH);


ALTER TABLE CC105613.INSPECOES
    ADD CONSTRAINT FK_INSPECOES_PROTOCOLO FOREIGN KEY (ID_PROTOCOLO_SEGURANCA) REFERENCES PROTOCOLOS_SEGURANCA (ID_PROTOCOLO_SEGURANCA);
ALTER TABLE CC105613.INSPECOES
    ADD CONSTRAINT FK_INSPECOES_ITEM FOREIGN KEY (ID_ITEM) REFERENCES ITENS (ID_ITEM);

COMMIT;