CREATE TABLE CAMINHAO
(
    PLACA          INT         NOT NULL,
    MARCA          VARCHAR(64) NOT NULL,
    MODELO         VARCHAR(64) NOT NULL,
    ANO_FABRICACAO INT         NOT NULL
);

ALTER TABLE CAMINHAO
    ADD CONSTRAINT PK_CAMINHAO PRIMARY KEY (PLACA);


CREATE TABLE CATEGORIAITEM
(
    ID_CATEGORIA NUMERIC(10) NOT NULL,
    DESCRICAO    VARCHAR(256)
);

ALTER TABLE CATEGORIAITEM
    ADD CONSTRAINT PK_CATEGORIAITEM PRIMARY KEY (ID_CATEGORIA);


CREATE TABLE CIDADE
(
    ID_CIDADE          NUMERIC(10) NOT NULL,
    NOME               INT,
    UNIDADE_FEDERATIVA NCHAR(2)
);

ALTER TABLE CIDADE
    ADD CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE);


CREATE TABLE CLIENTE
(
    IDCLIENTE NUMERIC(10) NOT NULL,
    NOME      INT,
    ENDERECO  INT,
    TELEFONES INT
);

ALTER TABLE CLIENTE
    ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (IDCLIENTE);


CREATE TABLE DISTANCIA
(
    ID_CIDADE_PARTIDA NUMERIC(10) NOT NULL,
    ID_CIDADE_CHEGADA NUMERIC(10) NOT NULL,
    DISTANCIA         INT
);

ALTER TABLE DISTANCIA
    ADD CONSTRAINT PK_DISTANCIA PRIMARY KEY (ID_CIDADE_PARTIDA, ID_CIDADE_CHEGADA);


CREATE TABLE ENDERECO
(
    CEP         NUMERIC(8),
    RUA         VARCHAR(64),
    NUMERO      NUMERIC(5),
    COMPLEMENTO NUMERIC(3),
    BAIRRO      VARCHAR(64),
    CIDADE      VARCHAR(64),
    ESTADO      NCHAR(2)
);


CREATE TABLE ENTREGA
(
    ID_ENTREGA        NUMERIC(10) NOT NULL,
    VALOR             INT,
    DATA_CHEGADA      DATE,
    DATA_PARTIDA      DATE,
    ID_CIDADE_PARTIDA NUMERIC(10),
    PLACA             VARCHAR(7),
    ID_CIDADE_CHEGADA NUMERIC(10),
    ID_CLIENTE        NUMERIC(10) NOT NULL
);

ALTER TABLE ENTREGA
    ADD CONSTRAINT PK_ENTREGA PRIMARY KEY (ID_ENTREGA);


CREATE TABLE ITEM
(
    IDITEM      NUMERIC(10) NOT NULL,
    DESCRICAO   VARCHAR(64) NOT NULL,
    PESO        INT         NOT NULL,
    LARGURA     INT         NOT NULL,
    COMPRIMENTO INT         NOT NULL,
    ALTURA      INT         NOT NULL
);

ALTER TABLE ITEM
    ADD CONSTRAINT PK_ITEM PRIMARY KEY (IDITEM);


CREATE TABLE LICITACAO
(
    INDICE_LICITACAO   NUMERIC(10) NOT NULL,
    ID_ITEM            NUMERIC(10) NOT NULL,
    ORGAO_FISCALIZADOR VARCHAR(64),
    DATA_LICITACAO     DATE        NOT NULL
);

ALTER TABLE LICITACAO
    ADD CONSTRAINT PK_LICITACAO PRIMARY KEY (INDICE_LICITACAO, ID_ITEM);


CREATE TABLE MOTORISTA
(
    CNH              NUMERIC(11) NOT NULL,
    DATA_CONTRATACAO DATE,
    NOME             VARCHAR(64),
    SALARIO          DECIMAL(10)
);

ALTER TABLE MOTORISTA
    ADD CONSTRAINT PK_MOTORISTA PRIMARY KEY (CNH);


CREATE TABLE PESSOAFISICA
(
    IDCLIENTE NUMERIC(10) NOT NULL,
    CPF       INT,
    RG        INT
);

ALTER TABLE PESSOAFISICA
    ADD CONSTRAINT PK_PESSOAFISICA PRIMARY KEY (IDCLIENTE);


CREATE TABLE PESSOAJURIDICA
(
    ID_CLIENTE         NUMERIC(10) NOT NULL,
    CNPJ               INT,
    INSCRICAO_ESTADUAL NUMERIC(10)
);

ALTER TABLE PESSOAJURIDICA
    ADD CONSTRAINT PK_PESSOAJURIDICA PRIMARY KEY (ID_CLIENTE);


CREATE TABLE PROTOCOLO_SEGURANCA
(
    ID_PROTOCOLO_SEGURANCA NUMERIC(10) NOT NULL,
    DESCRICAO              VARCHAR(256)
);

ALTER TABLE PROTOCOLO_SEGURANCA
    ADD CONSTRAINT PK_PROTOCOLO_SEGURANCA PRIMARY KEY (ID_PROTOCOLO_SEGURANCA);


CREATE TABLE REMESSA
(
    ID_ITEM         NUMERIC(10) NOT NULL,
    ID_ENTREGA      NUMERIC(10) NOT NULL,
    VALOR_DECLARADO DECIMAL(10)
);

ALTER TABLE REMESSA
    ADD CONSTRAINT PK_REMESSA PRIMARY KEY (ID_ITEM, ID_ENTREGA);


CREATE TABLE SEGURADORA
(
    NUMERO_SEGURADORA NUMERIC(10) NOT NULL,
    NOME              VARCHAR(64) NOT NULL
);

ALTER TABLE SEGURADORA
    ADD CONSTRAINT PK_SEGURADORA PRIMARY KEY (NUMERO_SEGURADORA);


CREATE TABLE TELEFONE
(
    DDD        INT,
    NUMERO     INT,
    ID_CLIENTE NUMERIC(10) NOT NULL
);


CREATE TABLE APOLICE
(
    ID_APOLICE        NUMERIC(10) NOT NULL,
    NUMERO_SEGURADORA NUMERIC(10) NOT NULL,
    ID_CLIENTE        NUMERIC(10) NOT NULL,
    VALOR_PREMIO      DECIMAL(3),
    VALOR_FRANQUIA    DECIMAL(3)
);

ALTER TABLE APOLICE
    ADD CONSTRAINT PK_APOLICE PRIMARY KEY (ID_APOLICE, NUMERO_SEGURADORA, ID_CLIENTE);


CREATE TABLE CATEGORIZACAO
(
    IDITEM       NUMERIC(10) NOT NULL,
    ID_CATEGORIA NUMERIC(10) NOT NULL
);

ALTER TABLE CATEGORIZACAO
    ADD CONSTRAINT PK_CATEGORIZACAO PRIMARY KEY (IDITEM, ID_CATEGORIA);


CREATE TABLE CONDUCAO
(
    ID_ENTREGA NUMERIC(10) NOT NULL,
    CNH        NUMERIC(11) NOT NULL
);

ALTER TABLE CONDUCAO
    ADD CONSTRAINT PK_CONDUCAO PRIMARY KEY (ID_ENTREGA, CNH);


CREATE TABLE INSPECOES
(
    ID_PROTOCOLO_SEGURANCA NUMERIC(10) NOT NULL,
    ID_ITEM                NUMERIC(10) NOT NULL,
    DATA_ULTIMA_INSPECAO   DATE
);

ALTER TABLE INSPECOES
    ADD CONSTRAINT PK_INSPECOES PRIMARY KEY (ID_PROTOCOLO_SEGURANCA, ID_ITEM);


ALTER TABLE DISTANCIA
    ADD CONSTRAINT FK_DISTANCIA_0 FOREIGN KEY (ID_CIDADE_PARTIDA) REFERENCES CIDADE (ID_CIDADE);
ALTER TABLE DISTANCIA
    ADD CONSTRAINT FK_DISTANCIA_1 FOREIGN KEY (ID_CIDADE_CHEGADA) REFERENCES CIDADE (ID_CIDADE);


ALTER TABLE ENTREGA
    ADD CONSTRAINT FK_ENTREGA_0 FOREIGN KEY (ID_CIDADE_PARTIDA) REFERENCES CIDADE (ID_CIDADE);
ALTER TABLE ENTREGA
    ADD CONSTRAINT FK_ENTREGA_1 FOREIGN KEY (PLACA) REFERENCES CAMINHAO (PLACA);
ALTER TABLE ENTREGA
    ADD CONSTRAINT FK_ENTREGA_2 FOREIGN KEY (ID_CIDADE_CHEGADA) REFERENCES CIDADE (ID_CIDADE);
ALTER TABLE ENTREGA
    ADD CONSTRAINT FK_ENTREGA_3 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE);


ALTER TABLE LICITACAO
    ADD CONSTRAINT FK_LICITACAO_0 FOREIGN KEY (ID_ITEM) REFERENCES ITEM (IDITEM);


ALTER TABLE PESSOAFISICA
    ADD CONSTRAINT FK_PESSOAFISICA_0 FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE);


ALTER TABLE PESSOAJURIDICA
    ADD CONSTRAINT FK_PESSOAJURIDICA_0 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE);


ALTER TABLE REMESSA
    ADD CONSTRAINT FK_REMESSA_0 FOREIGN KEY (ID_ITEM) REFERENCES ITEM (IDITEM);
ALTER TABLE REMESSA
    ADD CONSTRAINT FK_REMESSA_1 FOREIGN KEY (ID_ENTREGA) REFERENCES ENTREGA (ID_ENTREGA);


ALTER TABLE TELEFONE
    ADD CONSTRAINT FK_TELEFONE_0 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE);


ALTER TABLE APOLICE
    ADD CONSTRAINT FK_APOLICE_0 FOREIGN KEY (NUMERO_SEGURADORA) REFERENCES SEGURADORA (NUMERO_SEGURADORA);
ALTER TABLE APOLICE
    ADD CONSTRAINT FK_APOLICE_1 FOREIGN KEY (ID_CLIENTE) REFERENCES PESSOAJURIDICA (ID_CLIENTE);


ALTER TABLE CATEGORIZACAO
    ADD CONSTRAINT FK_CATEGORIZACAO_0 FOREIGN KEY (IDITEM) REFERENCES ITEM (IDITEM);
ALTER TABLE CATEGORIZACAO
    ADD CONSTRAINT FK_CATEGORIZACAO_1 FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAITEM (ID_CATEGORIA);


ALTER TABLE CONDUCAO
    ADD CONSTRAINT FK_CONDUCAO_0 FOREIGN KEY (ID_ENTREGA) REFERENCES ENTREGA (ID_ENTREGA);
ALTER TABLE CONDUCAO
    ADD CONSTRAINT FK_CONDUCAO_1 FOREIGN KEY (CNH) REFERENCES MOTORISTA (CNH);


ALTER TABLE INSPECOES
    ADD CONSTRAINT FK_INSPECOES_0 FOREIGN KEY (ID_PROTOCOLO_SEGURANCA) REFERENCES PROTOCOLO_SEGURANCA (ID_PROTOCOLO_SEGURANCA);
ALTER TABLE INSPECOES
    ADD CONSTRAINT FK_INSPECOES_1 FOREIGN KEY (ID_ITEM) REFERENCES ITEM (IDITEM);


